# AWS Image Manifest Format: $REGISTRY/$REPOSITORY:$IMAGE_TAG

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - when: never
  variables:
    CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE: "${CI_PROJECT_DIR}/dockerfile"
  parallel:
    matrix:
      - TAG: $IMAGE_TAG
      - TAG: latest
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CONTEXT --dockerfile $DOCKERFILE --destination $REGISTRY/$REPOSITORY:${IMAGE_NAME}_${TAG}
